version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes: 
      - .:/app
    depends_on: 
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_DATABASE: eureka
      MYSQL_USER: root
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_PASSWORD: toor
    volumes: 
      - .dbdata:/var/lib/mysql
    ports: 
      - 33066:3306